version: "3.11"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_DB
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A My_Project worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis